# Generated by Django 3.2.4 on 2021-07-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_auto_20210709_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='times_taken',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizz.player'),
        ),
    ]
