# Generated by Django 3.2.4 on 2021-07-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0007_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='quizz.player'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
